export default class Request extends stream.Duplex {
    constructor(opts: Opts, resCallback: any);
    _timeout: NodeJS.Timeout;
    socket: any;
    _currentRequest: http.ClientRequest;
    response: Response;
    responseStream: stream.Readable;
    timing: boolean;
    responseStarted: boolean;
    responseStartTime: number;
    _destdata: boolean;
    _paused: boolean;
    _respended: boolean;
    pipesrc: stream.Readable;
    pipedests: stream.Writable[];
    startTimer: any;
    opt: Opts;
    pipefilter: any;
    _currentUrl: string;
    headers: {
        [x: string]: string;
    };
    _ended: boolean;
    _ending: boolean;
    _redirectCount: number;
    _redirects: any[];
    _requestBodyLength: number;
    _requestBodyBuffers: any[];
    resCallback: any;
    _onResponse: (res: Response) => void;
    request(): http.ClientRequest;
    abort(): void;
    destroy(error: any): this;
    send(): void;
    override write(chunk: any, encoding?: BufferEncoding | ((error: Error | null) => void), cb?: (error: Error | null) => void): boolean;
    override end(chunk?: any, encoding?: BufferEncoding | (() => void), cb?: () => void): this;
    hasHeader(name: string): boolean;
    getHeader(name: string): string;
    setHeader(name: string, value: string): void;
    removeHeader(name: string): void;
    get headersSent(): boolean;
    setTimeout(msecs: any, callback: any): this;
    sanitizeOptions(options: any): void;
    processResponse(response: Response): void;
    _isRedirect: boolean;
    processStream(res: Response): Response | stream.Readable;
    override pipe<T>(dest: T & stream.Writable, opts?: {}): T;
    unpipe(dest: stream.Writable): this;
    pipeDest(dest: any): void;
    pause(): this;
    resume(): this;
}
export type Opts = {
    headers: {
        [x: string]: string;
    };
    host: string;
    method: string;
    family: string;
    path: string;
    protocol: "http:" | "https:";
    agent: any;
    agents: any;
    stream?: boolean;
    decompress?: boolean;
    transformStream?: any;
    beforeRedirect?: any;
    followRedirects?: boolean;
    maxRedirects?: number;
    maxBodyLength?: number;
    trackRedirects?: any;
    data?: any;
};
export type ResponseExt = {
    redirects?: any[];
    responseUrl?: string;
    responseStartTime?: number;
};
export type Response = http.IncomingMessage & ResponseExt;
import stream from 'node:stream';
import http from 'node:http';
